conf/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('admin/', admin.site.urls),
    path('produto/', include('produto.urls', namespace='produto')),
    path('entrada/', include('entrada.urls', namespace='entrada')),
    path('saida/', include('saida.urls', namespace='saida'))
]

entrada/urls.py
from django.urls import path
from .views import list_entrada, new_entrada, update_entrada, delete_entrada

app_name = 'entrada'

urlpatterns = [
    path('list_entrada', list_entrada, name='list_entrada'),
    path('new_entrada', new_entrada, name='new_entrada'),
    path('update_entrada/<int:pk>/', update_entrada, name='update_entrada'),
    path('delete_entrada/<int:pk>/', delete_entrada, name='delete_entrada')
]

produto/urls.py
from django.urls import path
from .views import list_produto, new_produto, update_produto, delete_produto

app_name = 'produto'

urlpatterns = [
    path('list_produto/', list_produto, name='list_produto'),
    path('new_produto/', new_produto, name='new_produto'),
    path('update_produto/<int:pk>/', update_produto, name='update_produto'),
    path('delete_produto/<int:pk>/', delete_produto, name='delete_produto')
]

entrada/models.py
from django.db import models
from produto.models import Produtos

# Create your models here.
class Entradas(models.Model):
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE, verbose_name= 'Produto')
    preco = models.FloatField('Preco', default=0)
    quantidade = models.IntegerField('Quantidade', default=0)
    criado = models.DateTimeField('Criado em', auto_now_add=True)
    modificado = models.DateTimeField('Modificado em', auto_now=True)

entrada/forms.py
from django.forms import ModelForm
from .models import Entradas

class EntradaForm(ModelForm):
    class Meta:
        model = Entradas
        fields = ['produto', 'quantidade']
        

entrada/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from .models import Entradas
from .forms import EntradaForm

def list_entrada(request):
    entradas = Entradas.objects.all()
    template_name = 'list_entrada.html'
    context = {
        'entradas': entradas
    }
    return render(request, template_name, context)


def new_entrada(request):
    if request.method == 'POST':
        form = EntradaForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            if form.cleaned_data['quantidade'] <= 0:
                form.add_error('quantidade', 'Insira apenas valores positivos')
                return render(request, 'new_entrada.html', {'form': form})
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade + form.cleaned_data['quantidade']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('entrada:list_entrada')
    
    else:
        template_name = 'new_entrada.html'
        context = {
            'form': EntradaForm()
        }
        return render(request, template_name, context)

def update_entrada(request, pk):
    entrada = Entradas.objects.get(pk=pk)
    quantidade = entrada.quantidade
    template_name = 'update_entrada.html'

    if request.method == 'POST':
        form = EntradaForm(request.POST,instance=entrada)
        if form.is_valid():
            form.save(commit=False)
            if form.cleaned_data['produto'].quantidade - quantidade + form.cleaned_data['quantidade'] <= 0:
                form.add_error('quantidade', 'Quantidade insuficiente em estoque.')
                return render(request, template_name, {'form': form, 'pk': pk})
            if form.cleaned_data['quantidade'] <= 0:
                form.add_error('quantidade', 'Insira apenas valores positivos')
                return render(request,template_name, {'form': form, 'pk': pk})
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade - quantidade + form.cleaned_data['quantidade']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('entrada:list_entrada')
    else:
        context = {
            'form': EntradaForm(instance=entrada),
            'pk': pk
        }
        return render(request, template_name, context)
        
def delete_entrada(request, pk): 
    entrada = Entradas.objects.get(pk=pk)     
    if entrada.produto.quantidade - entrada.quantidade <= 0:
        print("Não foi possivel excluir a entrada, pois o produto ficaria com quantidade negativa.")
        context = {
            'error': "Não foi possivel excluir a entrada, pois o produto ficaria com quantidade negativa.",
        }
        return render(request, 'error_entrada.html', context)
    entrada.produto.quantidade = entrada.produto.quantidade - entrada.quantidade
    entrada.produto.save()
    entrada.delete()
    return redirect('entrada:list_entrada')
            

entrada/templates/error_entrada.html
{% extends 'base.html' %}
{% block product %}
{% if error %}
<h1 class="subtitle is-3 has-text-primary">
  Remover Entrada
</h1>
<div>
  <nav class="navbar breadcrumb" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'entrada:list_entrada' %}">Pagina Inicial</a></li>
      <li><a href="{% url 'entrada:list_entrada' %}">Entradas</a></li>
      <li class="is-active"><a href="#">Remover Entrada</a></li>
    </ul>
  </nav>
</div>
<div class="alert alert-danger">
  {{ error }}
</div>
{% endif %}
{% endblock %}

entrada/templates/list_entrada.html
{% extends 'base.html' %}
{% block product %}
<h1 class="subtitle is-3 has-text-primary">
  Entradas
</h1>
<div>
  <nav class="navbar breadcrumb" aria-label="breadcrumbs">
      <ul>
          <li><a href="{% url 'produto:list_produto' %}">Pagina Inicial</a></li>
          <li class="is-active"><a href="#">Entradas</a></li>
      </ul>
      <div class="navbar-end">
          <a class="button has-text-primary" href="{% url 'entrada:new_entrada' %}">
              <span class="icon is-small mr-1">
                  <i class="fa-solid fa-plus"></i>
              </span>
              Novo
          </a>
      </div>
  </nav>
</div>
<table class="table is-striped is-hoverable is-fullwidth">
  <thead>
      <tr>
          <th>Id</th>
          <th>Produto</th>
          <th>Cor</th>
          <th>Quantidade</th>
          <th></th>
      </tr>
  </thead>
  <tbody>{% for entrada in entradas %}<tr>
      <th>{{ entrada.id }}</th>
      <td>{{ entrada.produto }}</td>
      <td>{{ entrada.produto.cor }}</td>
      <td class="is-flex justify-content is-justify-content-space-between">
        {{ entrada.quantidade }}
        <a href="{% url 'entrada:update_entrada' entrada.id%}">
            <i class="fa-solid fa-pen"></i>
            Editar
        </a>
        <a class="has-text-danger" href="{% url 'entrada:delete_entrada' entrada.id%}">
            <i class="fa-solid fa-trash"></i>
            Remover
        </a>
    </td>
    <td></td>
    </tr>{% endfor %} 
  </tbody>
</table>
{% endblock %}

entrada/templates/new_entrada.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block product %}
<h1 class="subtitle is-3 has-text-primary">
  Nova Entrada
</h1>
<div>
  <nav class="navbar breadcrumb" aria-label="breadcrumbs">
      <ul>
          <li class=""><a href="{% url 'entrada:list_entrada' %}">Pagina Inicial</a></li>
          <li><a href="{% url 'entrada:list_entrada' %}">Entradas</a></li>
          <li class="is-active"><a href="#">Nova Entrada</a></li>
      </ul>
  </nav>
</div>
<form action="{% url 'entrada:new_entrada' %}" method="POST">
  {% csrf_token %}
  <!-- {{ form.as_p }} -->
  {{ form|crispy }}
  <button class="button is-primary" type="submit">salvar</button>
</form>
{% endblock %}

entrada/templates/update_entrada.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block product %}
<h1 class="subtitle is-3 has-text-primary">
  Editar Entrada
</h1>
<div>
  <nav class="navbar breadcrumb" aria-label="breadcrumbs">
      <ul>
          <li><a href="{% url 'entrada:list_entrada' %}">Pagina Inicial</a></li>
          <li><a href="{% url 'entrada:list_entrada' %}">Entradas</a></li>
          <li class="is-active"><a href="#">Editar Entrada</a></li>
      </ul>
  </nav>
</div>
    <form action="{% url 'entrada:update_entrada' pk %}" method="POST">
      {% csrf_token %}
      <!-- {{ form.as_p }}  -->
      {{ form|crispy }}
      <button class="button is-primary mt-5" type="submit">salvar</button>
  </form>
{% endblock %}