conf/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('admin/', admin.site.urls),
    path('produto/', include('produto.urls', namespace='produto')),
    path('entrada/', include('entrada.urls', namespace='entrada')),
    path('saida/', include('saida.urls', namespace='saida'))
]

produto/urls.py
from django.urls import path
from .views import list_produto, new_produto, update_produto, delete_produto

app_name = 'produto'

urlpatterns = [
    path('list_produto/', list_produto, name='list_produto'),
    path('new_produto/', new_produto, name='new_produto'),
    path('update_produto/<int:pk>/', update_produto, name='update_produto'),
    path('delete_produto/<int:pk>/', delete_produto, name='delete_produto')
]

produto/models.py
from django.db import models

# Create your models here.
class Cores(models.Model):
    cor = models.CharField('Cor', max_length=200)
    
    def __str__(self):
        return self.cor
    
class Produtos(models.Model):
    produto = models.CharField('Produto', max_length=200)
    cor = models.ForeignKey(Cores, on_delete=models.PROTECT, verbose_name='Cor')
    descricao = models.TextField('Descriçao', blank=True)
    quantidade = models.IntegerField('Quantidade', default=0)
    preco = models.DecimalField('Preço', decimal_places=2, max_digits=8, default=0)
    criado = models.DateTimeField('Criado em', auto_now_add=True)
    modificado = models.DateField('Modificado em', auto_now=True)

    def __str__(self):
        return self.produto

    def precoQuantidade(self):
        return self.preco * self.quantidade
    
    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['-produto']

produto/forms.py
from django.forms import ModelForm 
from .models import Produtos 

class ProdutoForm(ModelForm): 
    class Meta:  
        model = Produtos
        fields = ['produto', 'cor', 'descricao', 'preco']

produto/views.py
from django.shortcuts import render, redirect
from .models import Produtos
from .forms import ProdutoForm

def list_produto(request): 
    produtos = Produtos.objects.all() 
    template_name = 'list_produtos.html' 
    context = { 'produtos': produtos, } 
    return render(request, template_name, context)

def new_produto(request): 
    if request.method == 'POST': 
        form = ProdutoForm(request.POST) 
        if form.is_valid(): 
            if form.cleaned_data['preco'] <= 0:
                form.add_error('preco', 'Insira apenas valores positivos.')
                return render(request, 'new_produto.html', {'form': form})
            form.save() 
            return redirect('produto:list_produto') 
    else:     
        template_name = 'new_produto.html'
        context = {'form': ProdutoForm(),}
        return render(request, template_name, context)
        

def update_produto(request, pk): 
    produto = Produtos.objects.get(pk=pk) 
    if request.method == 'POST': 
        form = ProdutoForm(request.POST, instance=produto) 
        if form.is_valid(): 
            print(form.cleaned_data['preco'])
            if form.cleaned_data['preco'] <= 0:
                form.add_error('preco', 'Insira apenas valores positivos.')
                return render(request, 'update_produto.html', {'form': form, 'pk': pk})
            form.save()
            return redirect('produto:list_produto') 
    else:      
        template_name = 'update_produto.html'
        context = {'form': ProdutoForm(instance=produto),'pk': pk,}
        return render(request, template_name, context)
        
def delete_produto(request, pk): 
    produto = Produtos.objects.get(pk=pk) 
    produto.delete() 
    return redirect('produto:list_produto')

produto/templates/list_produtos.html
{% extends 'base.html' %}
{% block product %}
<h1 class="subtitle is-3 has-text-primary">
    Produtos
</h1>
<div>
    <nav class="navbar breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li class="is-active"><a href="#">Pagina Inicial</a></li>
        </ul>
        <div class="navbar-end">
            <a class="button has-text-primary" href="{% url 'produto:new_produto' %}">
                <span class="icon is-small mr-1">
                    <i class="fa-solid fa-plus"></i>
                </span>
                Novo
            </a>
        </div>
    </nav>
</div>
<table class="table is-striped is-hoverable is-fullwidth">
    <thead>
        <tr>
            <th>Id</th>
            <th>Produto</th>
            <th>Cor</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th></th>
        </tr>
    </thead>
    <tbody> {% for produto in produtos %}<tr>
            <th>{{ produto.id }}</th>
            <td>{{ produto.produto }}</td>
            <td>{{ produto.cor }}</td>
            <td>{{ produto.preco }}</td>
            <td class="is-flex justify-content is-justify-content-space-between">
                {{ produto.quantidade }}
                <a href="{% url 'produto:update_produto' produto.id%}">
                    <i class="fa-solid fa-pen"></i>
                    Editar
                </a>
                <a class="has-text-danger" href="{% url 'produto:delete_produto' produto.id%}">
                    <i class="fa-solid fa-trash"></i>
                    Remover
                </a>
            </td>
            <td></td>
        </tr> {% endfor %}
    </tbody>
</table>
{% endblock %}

produto/templates/new_produto.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block product %}
<h1 class="subtitle is-3 has-text-primary">
    Novo Produto
</h1>
<div>
    <nav class="navbar breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li class=""><a href="{% url 'produto:list_produto' %}">Pagina Inicial</a></li>
            <li class="is-active"><a href="#">Novo Produto</a></li>
        </ul>
    </nav>
</div>
<form action="{% url 'produto:new_produto' %}" method="POST">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
      {{ form|crispy }}
    <button class="button is-primary mt-5" type="submit">salvar</button>
</form>
{% endblock %}

produto/templates/update_produto.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block product %}
<h1 class="subtitle is-3 has-text-primary">
    Editar Produto
</h1>
<div>
    <nav class="navbar breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li class=""><a href="{% url 'produto:list_produto' %}">Pagina Inicial</a></li>
            <li class="is-active"><a href="#">Editar Produto</a></li>
        </ul>
    </nav>
</div>
<form action="{% url 'produto:update_produto' pk %}" method="post">
    {% csrf_token %}
    <!-- {{ form.as_p }}  -->
    {{ form|crispy }}
    <button class="button is-primary mt-5" type="submit">salvar</button>
</form>
{% endblock %}