conf/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('admin/', admin.site.urls),
    path('produto/', include('produto.urls', namespace='produto')),
    path('entrada/', include('entrada.urls', namespace='entrada')),
    path('saida/', include('saida.urls', namespace='saida'))
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', index, name='index'),
    #path('produto/', include('produto.urls', namespace='produto')),
    path('admin/', admin.site.urls),
]

entrada/urls.py
from django.urls import path
from .views import list_entrada, new_entrada, update_entrada, delete_entrada

app_name = 'entrada'

urlpatterns = [
    path('list_entrada', list_entrada, name='list_entrada'),
    path('new_entrada', new_entrada, name='new_entrada'),
    path('update_entrada/<int:pk>/', update_entrada, name='update_entrada'),
    path('delete_entrada/<int:pk>/', delete_entrada, name='delete_entrada')
]

produto/urls.py
from django.urls import path
from .views import list_produto, new_produto, update_produto, delete_produto

app_name = 'produto'

urlpatterns = [
    path('list_produto/', list_produto, name='list_produto'),
    path('new_produto/', new_produto, name='new_produto'),
    path('update_produto/<int:pk>/', update_produto, name='update_produto'),
    path('delete_produto/<int:pk>/', delete_produto, name='delete_produto')
]

saida/urls.py
from django.urls import path
from .views import list_saida, new_saida, update_saida, delete_saida

app_name = 'saida'

urlpatterns = [
    path('list_saida', list_saida, name='list_saida'),
    path('new_saida', new_saida, name='new_saida'),
    path('update_saida/<int:pk>/', update_saida, name='update_saida'),
    path('delete_saida/<int:pk>/', delete_saida, name='delete_saida')
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    template_name = 'index.html'
    context = {
        'mensagem': 'Bem vindo à aplicação estoqueWeb'
    }
    return render(request, template_name, context)

core/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css">
  <script src="https://kit.fontawesome.com/a49a7d283e.js" crossorigin="anonymous"></script>
  <title>Estoque</title>
  <link rel="icon" type="image/png" href="https://img.icons8.com/?size=100&id=ulguRNDTXFDs&format=png&color=000000">

</head>

<body>
  <nav class="navbar mr-6 ml-5 mt-6 mb-3">
    <a class="navbar-brand" href="{% url 'index' %}">
      <h1 class="title">
        <span class="icon is-small mr-3">
          <i class="fa-solid fa-box-open"></i>
        </span>
        Estoque
      </h1>
    </a>
    <div class="navbar-end">
      <h2 class="subtitle is-6 has-text-primary">by Lucas Viana</h2>
    </div>
  </nav>
  <!-- <a href="{% url 'produto:list_produto' %}">Produtos</a> -->
  <!-- <a href="{% url 'entrada:list_entrada' %}">Entradas</a>
    <a href="{% url 'saida:list_saida' %}">Saídas</a> -->
  <div class="columns is-mobile" style="height: 100%;">
    <!-- Menu lateral -->
    <div class="column is-2 sidebar">
      <aside class="menu p-3">
        <p class="menu-label">GERENCIAMENTO</p>
        <ul class="menu-list">
          <li><a href="{% url 'produto:list_produto' %}">Produtos</a></li>
        </ul>

        <p class="menu-label">MOVIMENTAÇÃO</p>
        <ul class="menu-list">
          <li><a href="{% url 'entrada:list_entrada' %}">Entradas</a></li>
          <li><a href="{% url 'saida:list_saida' %}">Saídas</a></li>
        </ul>
      </aside>
    </div>

    <!-- Conteúdo principal -->
    <div class="column" style="margin-right: 10rem;">
      <!-- <h1 class="title">Dashboard</h1> -->
      {% block product %}{% endblock %}
    </div>
  </div>
</body>

</html>

core/templates/index.html
{% extends 'base.html' %}
{% block product %}
<h1 class="title">Aplicação</h1>
    <article class="message">
        <div class="message-header">
          <p>Estoque</p>
          <a class="button is-success"  href="{% url 'produto:list_produto' %}">Iniciar</a>
        </div>
        <div class="message-body">
            O Estoque é uma aplicação voltada para o controle e gerenciamento de produtos. Com ela, o usuário pode
            <strong>cadastrar novos itens</strong> com informações como nome, categoria, unidade e preço. Além disso, é possível registrar
            <strong>entradas</strong> de produtos (como compras ou reposições) e <strong>saídas</strong>  (como vendas ou consumo interno). A aplicação atualiza
            automaticamente o saldo em estoque, facilitando o acompanhamento em tempo real. Tudo isso de forma simples,
            organizada e acessível via painel web.
        </div>
      </article>
{% endblock %}