conf/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('admin/', admin.site.urls),
    path('produto/', include('produto.urls', namespace='produto')),
    path('entrada/', include('entrada.urls', namespace='entrada')),
    path('saida/', include('saida.urls', namespace='saida'))
]

produto/urls.py
from django.urls import path
from .views import list_produto, new_produto, update_produto, delete_produto

app_name = 'produto'

urlpatterns = [
    path('list_produto/', list_produto, name='list_produto'),
    path('new_produto/', new_produto, name='new_produto'),
    path('update_produto/<int:pk>/', update_produto, name='update_produto'),
    path('delete_produto/<int:pk>/', delete_produto, name='delete_produto')
]

saida/urls.py
from django.urls import path
from .views import list_saida, new_saida, update_saida, delete_saida

app_name = 'saida'

urlpatterns = [
    path('list_saida', list_saida, name='list_saida'),
    path('new_saida', new_saida, name='new_saida'),
    path('update_saida/<int:pk>/', update_saida, name='update_saida'),
    path('delete_saida/<int:pk>/', delete_saida, name='delete_saida')
]

saida/models.py
from django.db import models
from produto.models import Produtos

# Create your models here.
class Saidas(models.Model):
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE, verbose_name='Produto')
    preco = models.FloatField('Preco', default=0)
    quantidade = models.IntegerField('Quantidade', default=0)
    criado = models.DateTimeField('Criado em', auto_now_add=True)
    modificado = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return f'{self.produto.nome} - {self.quantidade} unidades'

saida/forms.py
from django.forms import ModelForm
from .models import Saidas

class SaidaForm(ModelForm):
    class Meta:
        model = Saidas
        fields = ['produto', 'quantidade']
        

saida/views.py
from django.shortcuts import render, redirect
from .models import Saidas
from .forms import SaidaForm

# Create your views here.
def list_saida(request):
    saidas = Saidas.objects.all()
    template_name = 'list_saida.html'
    context = {
        'saidas': saidas
    }
    return render(request, template_name, context)

def new_saida(request):
    if request.method == 'POST':
        form = SaidaForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            if form.cleaned_data['quantidade'] > form.cleaned_data['produto'].quantidade:
                form.add_error('quantidade', 'Quantidade insuficiente em estoque.')
                return render(request, 'new_saida.html', {'form': form})
            if form.cleaned_data['quantidade'] <= 0:
                form.add_error('quantidade', 'Insira apenas valores positivos maiores que zero.')
                return render(request, 'new_saida.html', {'form': form})
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade - form.cleaned_data['quantidade']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('saida:list_saida')
    
    else:
        template_name = 'new_saida.html'
        context = {
            'form': SaidaForm()
        }
        return render(request, template_name, context)

def update_saida(request, pk):
    saida = Saidas.objects.get(pk=pk)
    quantidade = saida.quantidade
    template_name = 'update_saida.html'
    if request.method == 'POST':
        form = SaidaForm(request.POST,instance=saida)
        if form.is_valid():
            form.save(commit=False)
            if form.cleaned_data['quantidade'] > form.cleaned_data['produto'].quantidade + quantidade:
                form.add_error('quantidade', 'Quantidade insuficiente em estoque.')
                return render(request, template_name, {'form': form, 'pk': pk})
            if form.cleaned_data['quantidade'] <= 0:
                form.add_error('quantidade', 'Insira apenas valores positivos maiores que zero.')
                return render(request, template_name, {'form': form, 'pk': pk})
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade + quantidade - form.cleaned_data['quantidade']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('saida:list_saida')
    else:
        context = {
            'form': SaidaForm(instance=saida),
            'pk': pk
        }
        return render(request, template_name, context)
    

def delete_saida(request, pk): 
    saida = Saidas.objects.get(pk=pk)     
    saida.produto.quantidade = saida.produto.quantidade + saida.quantidade
    saida.produto.save()
    saida.delete()
    return redirect('saida:list_saida')

saida/templates/list_saida.html
{% extends 'base.html' %}
{% block product %}
<h1 class="subtitle is-3 has-text-primary">
  Saídas
</h1>
<div>
  <nav class="navbar breadcrumb" aria-label="breadcrumbs">
      <ul>
          <li><a href="{% url 'produto:list_produto' %}">Pagina Inicial</a></li>
          <li class="is-active"><a href="#">Saídas</a></li>
      </ul>
      <div class="navbar-end">
          <a class="button has-text-primary" href="{% url 'saida:new_saida' %}">
              <span class="icon is-small mr-1">
                  <i class="fa-solid fa-plus"></i>
              </span>
              Novo
          </a>
      </div>
  </nav>
</div>
<table class="table is-striped is-hoverable is-fullwidth">
  <thead>
    <tr>
      <th>Id</th>
      <th>Produto</th>
      <th>Cor</th>
      <th>Quantidade</th>
      <th></th>
  </tr>
  </thead>
  <tbody>{% for saida in saidas %}<tr>
      <th>{{ saida.id }}</th>
      <td>{{ saida.produto }}</td>
      <td>{{ saida.produto.cor }}</td>
      <td class="is-flex justify-content is-justify-content-space-between">
        {{ saida.quantidade }}
        <a href="{% url 'saida:update_saida' saida.id%}">
            <i class="fa-solid fa-pen"></i>
            Editar
        </a>
        <a class="has-text-danger" href="{% url 'saida:delete_saida' saida.id%}">
            <i class="fa-solid fa-trash"></i>
            Remover
        </a>
    </td>
    <td></td>
    </tr>{% endfor %} 
  </tbody>
</table>
{% endblock %}

saida/templates/new_saida.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block product %}
<h1 class="subtitle is-3 has-text-primary">
  Nova Saída
</h1>
<div>
  <nav class="navbar breadcrumb" aria-label="breadcrumbs">
      <ul>
          <li class=""><a href="{% url 'saida:list_saida' %}">Pagina Inicial</a></li>
          <li><a href="{% url 'saida:list_saida' %}">Saídas</a></li>
          <li class="is-active"><a href="#">Nova Saída</a></li>
      </ul>
  </nav>
</div>
<form action="{% url 'saida:new_saida' %}" method="POST">
  {% csrf_token %}
  <!-- {{ form.as_p }} -->
  {{ form|crispy }}
  <button class="button is-primary" type="submit">salvar</button>
</form>
{% endblock %}

saida/templates/update_saida.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block product %}
<h1 class="subtitle is-3 has-text-primary">
  Editar Saída
</h1>
<div>
  <nav class="navbar breadcrumb" aria-label="breadcrumbs">
      <ul>
          <li><a href="{% url 'saida:list_saida' %}">Pagina Inicial</a></li>
          <li><a href="{% url 'saida:list_saida' %}">Saídas</a></li>
          <li class="is-active"><a href="#">Editar Saída</a></li>
      </ul>
  </nav>
</div>
    <form action="{% url 'saida:update_saida' pk %}" method="POST">
      {% csrf_token %}
      <!-- {{ form.as_p }}  -->
      {{ form|crispy }}
      <button class="button is-primary mt-5" type="submit">salvar</button>
  </form>
{% endblock %}